cloudcomponents/cdk-constructs

- packages/cdk-codepipeline-slack-lambda/package.json
> fix: Missing @slack/web-api

- packages/cdk-static-website/src/static-website.ts
- packages/cdk-static-website/src/website-alias-record.ts
Also added optional override to disable them if someone wants to.
> Added support for AAAA records by default

- packages/cdk-codepipeline-slack/src/lambdas/shared/process-codepipeline.ts
> fix: Add missing channel id param

- examples/static-website-example/package.json
- examples/static-website-example/src/static-website-stack.ts
- packages/cdk-static-website/README.md
* Added a sample how to use existing sources for static web pages
* Added documentation about how to use existing sources for static web pages
Hope this might help to improve the documenation and samples
> Docs and sample: How to use existing sources for static website

- .vscode/settings.json
- examples/blue-green-container-deployment-example/src/blue-green-container-deployment-stack.ts
- packages/cdk-blue-green-container-deployment/src/ecs-deployment-group.ts
- packages/cdk-blue-green-container-deployment/src/lambdas/ecs-deployment-group/index.ts
> feat: Add terminationWaitTimeInMinutes

- examples/codepipeline-slack-approval-example/src/codepipeline-slack-approval-app.ts
- package.json
- packages/cdk-codepipeline-slack/src/lambdas/approval-handler/index.ts
- packages/cdk-codepipeline-slack/src/lambdas/shared/approval-interactions.ts
- packages/cdk-codepipeline-slack/src/lambdas/shared/approval-message-builder.ts
- packages/cdk-codepipeline-slack/src/lambdas/shared/message-builder.ts
- packages/cdk-codepipeline-slack/src/lambdas/shared/message.ts
- packages/cdk-codepipeline-slack/src/lambdas/shared/notifier-message-builder.ts
- packages/cdk-codepipeline-slack/src/lambdas/shared/slack-bot.ts
> fix: slack integration

- packages/cdk-codecommit-backup/scripts/backup_codecommit.sh
- packages/cdk-codecommit-backup/src/__tests__/__snapshots__/full-region-s3-codecommit-backup.test.ts.snap
> fix: Reading a delimited string into an array

- packages/cdk-pull-request-approval-rule/src/__tests__/__snapshots__/approval-rule-template.test.ts.snap
- packages/cdk-pull-request-approval-rule/src/__tests__/approval-rule-template.test.ts
- packages/cdk-pull-request-approval-rule/src/approval-rule-template.ts
> fix: Allow list of ApprovalPoolMembers

- packages/cdk-cloudfront-authorization/src/distributions.ts
> fix: Add support for alternate domain names

- packages/cdk-static-website/API.md
- packages/cdk-static-website/src/__tests__/__snapshots__/static-website.test.ts.snap
- packages/cdk-static-website/src/__tests__/static-website.test.ts
- packages/cdk-static-website/src/static-website.ts
feat: cdk-static-website support errorConfigurations props
close #68
> feat: cdk-static-website support errorConfigurations props

- packages/cdk-blue-green-container-deployment/src/dummy-task-definition.ts
- packages/cdk-cloudfront-authorization/src/__tests__/__snapshots__/authorizations.test.ts.snap
- packages/cdk-cloudfront-authorization/src/__tests__/__snapshots__/distributions.test.ts.snap
- packages/cdk-lambda-at-edge-pattern/src/__tests__/__snapshots__/http-headers.test.ts.snap
- packages/cdk-lambda-at-edge-pattern/src/edge-function.ts
- packages/cdk-pull-request-check/src/__tests__/__snapshots__/pull-request-check.test.ts.snap
- packages/cdk-pull-request-check/src/pull-request-check.ts
> fix: Deprecation warnings uniqueId

- packages/cdk-lambda-at-edge-pattern/src/base-edge-construct.ts
- packages/cdk-lambda-at-edge-pattern/src/edge-function.ts
- Add nested Stack support
fixes #79
> fix: Add nestedStack support

- packages/cdk-developer-tools-notifications/src/notification-rules.ts
> fix: Typo in enum ProjectEvent

- packages/cdk-chatops/API.md
- packages/cdk-chatops/src/msteams-incoming-webhook-configuration.ts
> fix: Change incomingWebhook visibility

- packages/cdk-pull-request-check/src/pull-request-check.ts
Pass environmentVariables to CodeBuild project.
> Add environmentVariables property to PullRequestCheckProps

- packages/cdk-lambda-at-edge-pattern/README.md
- packages/cdk-lambda-at-edge-pattern/src/__tests__/__snapshots__/origin-mutation.test.ts.snap
- packages/cdk-lambda-at-edge-pattern/src/__tests__/origin-mutation.test.ts
- packages/cdk-lambda-at-edge-pattern/src/lambdas/origin-mutation/index.ts
- packages/cdk-lambda-at-edge-pattern/src/origin-mutation.ts
> feat: Add origin mutation

- packages/cdk-pull-request-check/package-lock.json
- packages/cdk-pull-request-check/src/__tests__/__snapshots__/pull-request-check.test.ts.snap
- packages/cdk-pull-request-check/src/__tests__/pull-request-check.test.ts
- packages/cdk-pull-request-check/src/lambdas/code-build-result/index.ts
When a pull request check build has a custom environment variable, the Lambda approving the pull request would fail due to an unknown environment variable. I simply removed the error handling. The environment variables that are unknown, cause no harm.
> Support custom environment variables in a pull request check

- packages/cdk-pull-request-check/src/__tests__/__snapshots__/pull-request-check.test.ts.snap
- packages/cdk-pull-request-check/src/pull-request-check.ts
Ensure we can use configured artifacts for CodeBuild Pull Request Check Project.
> Remove artifactsOverrides from Pull Request Check Rule, serves no purpose.

- packages/cdk-blue-green-container-deployment/src/ecs-service.ts
> fix: Property name

- packages/cdk-static-website/src/static-website.ts
Small, trivial, cosmetic change.
Thanks for making cdk-constructs! Great resource.
> fix spelling in static-website.ts

- examples/codecommit-backup-example/package.json
- examples/codecommit-backup-example/src/codecommit-backup-app.ts
- examples/codecommit-backup-example/src/codecommit-backup-stack.ts
- packages/cdk-codecommit-backup/API.md
- packages/cdk-codecommit-backup/package.json
- packages/cdk-codecommit-backup/src/__tests__/__snapshots__/backup-bucket.test.ts.snap
- packages/cdk-codecommit-backup/src/__tests__/__snapshots__/full-region-s3-codecommit-backup.test.ts.snap
- packages/cdk-codecommit-backup/src/__tests__/__snapshots__/s3-codecommit-backup.test.ts.snap
- packages/cdk-codecommit-backup/src/__tests__/backup-bucket.test.ts
- packages/cdk-codecommit-backup/src/__tests__/full-region-s3-codecommit-backup.test.ts
- packages/cdk-codecommit-backup/src/__tests__/s3-codecommit-backup.test.ts
- packages/cdk-codecommit-backup/src/backup-bucket.ts
- packages/cdk-codecommit-backup/src/full-region-s3-codecommit-backup.ts
- packages/cdk-codecommit-backup/src/s3-codecommit-backup.ts
Migration of cdk-codecommit-backup to cdkv2. Change to buildImage to the latest version
> Migrate codecommit backup
